
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Grupo10 TP3 Ejercicio 1
 * Altamirano Karina
 * Gianfranco Antonacci Matías
 * Bequis Marcos Ezequiel
 * Dave  Natalia
 * Quiroga Dorzan Alejo
 * Franzinni Tatiana
 */
public class ConversorTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form ConversorTemperatura
     */
    public ConversorTemperatura() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        bgrMedidaSalida = new javax.swing.ButtonGroup();
        bgrMedidaEntrada = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonConvertir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jrbCelsiusFahrenheit = new javax.swing.JRadioButton();
        jrbFahrenheitCelsius = new javax.swing.JRadioButton();
        jrbCelsiusKelvin = new javax.swing.JRadioButton();
        jrbKelvinCelsius = new javax.swing.JRadioButton();
        jrbCelsiusRadianes = new javax.swing.JRadioButton();
        jrbRadianesCelsius = new javax.swing.JRadioButton();
        jrbFahrenheitKelvin = new javax.swing.JRadioButton();
        jrbKelvinFahrenheit = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(168, 247, 247));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Ingrese la temperatura");

        jButtonConvertir.setBackground(new java.awt.Color(153, 255, 255));
        jButtonConvertir.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reload.png"))); // NOI18N
        jButtonConvertir.setText("Convertir");
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Conversor de Temperatura");

        bgrMedidaSalida.add(jrbCelsiusFahrenheit);
        jrbCelsiusFahrenheit.setText("A Celsius");
        jrbCelsiusFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCelsiusFahrenheitActionPerformed(evt);
            }
        });

        bgrMedidaSalida.add(jrbFahrenheitCelsius);
        jrbFahrenheitCelsius.setText("A Fahrenheit");
        jrbFahrenheitCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFahrenheitCelsiusActionPerformed(evt);
            }
        });

        bgrMedidaSalida.add(jrbCelsiusKelvin);
        jrbCelsiusKelvin.setText("A Kelvin");

        bgrMedidaSalida.add(jrbKelvinCelsius);
        jrbKelvinCelsius.setText("A Radianes");

        bgrMedidaEntrada.add(jrbCelsiusRadianes);
        jrbCelsiusRadianes.setText("De Celsius");
        jrbCelsiusRadianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCelsiusRadianesActionPerformed(evt);
            }
        });

        bgrMedidaEntrada.add(jrbRadianesCelsius);
        jrbRadianesCelsius.setText("De Farenheit");

        bgrMedidaEntrada.add(jrbFahrenheitKelvin);
        jrbFahrenheitKelvin.setText("De Kelvin");

        bgrMedidaEntrada.add(jrbKelvinFahrenheit);
        jrbKelvinFahrenheit.setText("De Radianes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbFahrenheitKelvin)
                            .addComponent(jrbKelvinFahrenheit))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbCelsiusKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbKelvinCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbRadianesCelsius)
                            .addComponent(jrbCelsiusRadianes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbCelsiusFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbFahrenheitCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButtonConvertir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)))
                .addGap(98, 98, 98))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbCelsiusFahrenheit)
                    .addComponent(jrbCelsiusRadianes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbFahrenheitCelsius)
                    .addComponent(jrbRadianesCelsius))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbCelsiusKelvin)
                    .addComponent(jrbFahrenheitKelvin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbKelvinCelsius)
                    .addComponent(jrbKelvinFahrenheit))
                .addGap(18, 18, 18)
                .addComponent(jButtonConvertir)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //-- Action del boton Convertir --
    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
     // Acción del botón convertir
        
        
            // Obtenemos el valor ingresado en el campo de texto
            String input = jTextField1.getText().trim();
            {
            if (input.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor numérico", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                double valor = Double.parseDouble(input);

                    // Identificar qué radio button está seleccionado
                    if (jrbCelsiusFahrenheit.isSelected()) {
                        JOptionPane.showMessageDialog(null, "De Celsius a Fahrenheit (falta lógica)");
                    } else if (jrbFahrenheitCelsius.isSelected()) {
                        JOptionPane.showMessageDialog(null, "De Fahrenheit a Celsius (falta lógica)");
                    } else if (jrbCelsiusKelvin.isSelected()) {
                        JOptionPane.showMessageDialog(null, "De Celsius a Kelvin (falta lógica)");
                    } else if (jrbKelvinCelsius.isSelected()) {
                        JOptionPane.showMessageDialog(null, "De Kelvin a Celsius (falta lógica)");
                    } else if (jrbCelsiusRadianes.isSelected()) {
                        JOptionPane.showMessageDialog(null, "De Celsius a Radianes (falta lógica)");
                    } else if (jrbRadianesCelsius.isSelected()) {
                        JOptionPane.showMessageDialog(null, "De Radianes a Celsius (falta lógica)");
                    } else if (jrbFahrenheitKelvin.isSelected()) {
                        JOptionPane.showMessageDialog(null, "De Fahrenheit a Kelvin (falta lógica)");
                    } else if (jrbKelvinFahrenheit.isSelected()) {
                        JOptionPane.showMessageDialog(null, "De Kelvin a Fahrenheit (falta lógica)");
                    } else {
                        JOptionPane.showMessageDialog(null, "Seleccione una opción de conversión");
                    }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Valor inválido. Ingrese un número", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    
    
          
              

    }//GEN-LAST:event_jButtonConvertirActionPerformed

    private void jrbFahrenheitCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFahrenheitCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbFahrenheitCelsiusActionPerformed

    private void jrbCelsiusRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCelsiusRadianesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbCelsiusRadianesActionPerformed

    private void jrbCelsiusFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCelsiusFahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbCelsiusFahrenheitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrMedidaEntrada;
    private javax.swing.ButtonGroup bgrMedidaSalida;
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton jrbCelsiusFahrenheit;
    private javax.swing.JRadioButton jrbCelsiusKelvin;
    private javax.swing.JRadioButton jrbCelsiusRadianes;
    private javax.swing.JRadioButton jrbFahrenheitCelsius;
    private javax.swing.JRadioButton jrbFahrenheitKelvin;
    private javax.swing.JRadioButton jrbKelvinCelsius;
    private javax.swing.JRadioButton jrbKelvinFahrenheit;
    private javax.swing.JRadioButton jrbRadianesCelsius;
    // End of variables declaration//GEN-END:variables
}

